//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jadet.AdministradorServicio {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseRequest", Namespace="http://schemas.datacontract.org/2004/07/SernaSistemas.Jadet.WCF.Modelos")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Jadet.AdministradorServicio.ArchivoRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Jadet.AdministradorServicio.ProductoRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Jadet.AdministradorServicio.NotaRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Jadet.AdministradorServicio.GuiaRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Jadet.AdministradorServicio.ClienteRequest))]
    public partial class BaseRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ArchivoRequest", Namespace="http://schemas.datacontract.org/2004/07/SernaSistemas.Jadet.WCF.Modelos")]
    [System.SerializableAttribute()]
    public partial class ArchivoRequest : Jadet.AdministradorServicio.BaseRequest {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaCargaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LongitudField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RutaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoArchivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime UltimaModificacionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaCarga {
            get {
                return this.FechaCargaField;
            }
            set {
                if ((this.FechaCargaField.Equals(value) != true)) {
                    this.FechaCargaField = value;
                    this.RaisePropertyChanged("FechaCarga");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Longitud {
            get {
                return this.LongitudField;
            }
            set {
                if ((this.LongitudField.Equals(value) != true)) {
                    this.LongitudField = value;
                    this.RaisePropertyChanged("Longitud");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ruta {
            get {
                return this.RutaField;
            }
            set {
                if ((object.ReferenceEquals(this.RutaField, value) != true)) {
                    this.RutaField = value;
                    this.RaisePropertyChanged("Ruta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoArchivo {
            get {
                return this.TipoArchivoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoArchivoField, value) != true)) {
                    this.TipoArchivoField = value;
                    this.RaisePropertyChanged("TipoArchivo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime UltimaModificacion {
            get {
                return this.UltimaModificacionField;
            }
            set {
                if ((this.UltimaModificacionField.Equals(value) != true)) {
                    this.UltimaModificacionField = value;
                    this.RaisePropertyChanged("UltimaModificacion");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductoRequest", Namespace="http://schemas.datacontract.org/2004/07/SernaSistemas.Jadet.WCF.Modelos")]
    [System.SerializableAttribute()]
    public partial class ProductoRequest : Jadet.AdministradorServicio.BaseRequest {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NotaRequest", Namespace="http://schemas.datacontract.org/2004/07/SernaSistemas.Jadet.WCF.Modelos")]
    [System.SerializableAttribute()]
    public partial class NotaRequest : Jadet.AdministradorServicio.BaseRequest {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GuiaRequest", Namespace="http://schemas.datacontract.org/2004/07/SernaSistemas.Jadet.WCF.Modelos")]
    [System.SerializableAttribute()]
    public partial class GuiaRequest : Jadet.AdministradorServicio.BaseRequest {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClienteRequest", Namespace="http://schemas.datacontract.org/2004/07/SernaSistemas.Jadet.WCF.Modelos")]
    [System.SerializableAttribute()]
    public partial class ClienteRequest : Jadet.AdministradorServicio.BaseRequest {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdClienteField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCliente {
            get {
                return this.IdClienteField;
            }
            set {
                if ((this.IdClienteField.Equals(value) != true)) {
                    this.IdClienteField = value;
                    this.RaisePropertyChanged("IdCliente");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseResponse", Namespace="http://schemas.datacontract.org/2004/07/SernaSistemas.Jadet.WCF.Modelos")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Jadet.AdministradorServicio.ArchivoResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Jadet.AdministradorServicio.HistorialClienteResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Jadet.AdministradorServicio.ProductoResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Jadet.AdministradorServicio.coleccionProductoResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Jadet.AdministradorServicio.coleccionNotasResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Jadet.AdministradorServicio.NotaResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Jadet.AdministradorServicio.GuiaResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Jadet.AdministradorServicio.ClienteResponse))]
    public partial class BaseResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ErrorNumeroField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMensaje {
            get {
                return this.ErrorMensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMensajeField, value) != true)) {
                    this.ErrorMensajeField = value;
                    this.RaisePropertyChanged("ErrorMensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ErrorNumero {
            get {
                return this.ErrorNumeroField;
            }
            set {
                if ((this.ErrorNumeroField.Equals(value) != true)) {
                    this.ErrorNumeroField = value;
                    this.RaisePropertyChanged("ErrorNumero");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ArchivoResponse", Namespace="http://schemas.datacontract.org/2004/07/SernaSistemas.Jadet.WCF.Modelos")]
    [System.SerializableAttribute()]
    public partial class ArchivoResponse : Jadet.AdministradorServicio.BaseResponse {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HistorialClienteResponse", Namespace="http://schemas.datacontract.org/2004/07/SernaSistemas.Jadet.WCF.Modelos")]
    [System.SerializableAttribute()]
    public partial class HistorialClienteResponse : Jadet.AdministradorServicio.BaseResponse {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductoResponse", Namespace="http://schemas.datacontract.org/2004/07/SernaSistemas.Jadet.WCF.Modelos")]
    [System.SerializableAttribute()]
    public partial class ProductoResponse : Jadet.AdministradorServicio.BaseResponse {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="coleccionProductoResponse", Namespace="http://schemas.datacontract.org/2004/07/SernaSistemas.Jadet.WCF.Modelos")]
    [System.SerializableAttribute()]
    public partial class coleccionProductoResponse : Jadet.AdministradorServicio.BaseResponse {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Jadet.AdministradorServicio.ProductoResponse[] ItemsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Jadet.AdministradorServicio.ProductoResponse[] Items {
            get {
                return this.ItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemsField, value) != true)) {
                    this.ItemsField = value;
                    this.RaisePropertyChanged("Items");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="coleccionNotasResponse", Namespace="http://schemas.datacontract.org/2004/07/SernaSistemas.Jadet.WCF.Modelos")]
    [System.SerializableAttribute()]
    public partial class coleccionNotasResponse : Jadet.AdministradorServicio.BaseResponse {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Jadet.AdministradorServicio.NotaResponse[] ItemsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Jadet.AdministradorServicio.NotaResponse[] Items {
            get {
                return this.ItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemsField, value) != true)) {
                    this.ItemsField = value;
                    this.RaisePropertyChanged("Items");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NotaResponse", Namespace="http://schemas.datacontract.org/2004/07/SernaSistemas.Jadet.WCF.Modelos")]
    [System.SerializableAttribute()]
    public partial class NotaResponse : Jadet.AdministradorServicio.BaseResponse {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GuiaResponse", Namespace="http://schemas.datacontract.org/2004/07/SernaSistemas.Jadet.WCF.Modelos")]
    [System.SerializableAttribute()]
    public partial class GuiaResponse : Jadet.AdministradorServicio.BaseResponse {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NUmeroGuiaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NUmeroGuia {
            get {
                return this.NUmeroGuiaField;
            }
            set {
                if ((object.ReferenceEquals(this.NUmeroGuiaField, value) != true)) {
                    this.NUmeroGuiaField = value;
                    this.RaisePropertyChanged("NUmeroGuia");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClienteResponse", Namespace="http://schemas.datacontract.org/2004/07/SernaSistemas.Jadet.WCF.Modelos")]
    [System.SerializableAttribute()]
    public partial class ClienteResponse : Jadet.AdministradorServicio.BaseResponse {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AdministradorServicio.IAdministrador")]
    public interface IAdministrador {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministrador/guardarCliente", ReplyAction="http://tempuri.org/IAdministrador/guardarClienteResponse")]
        Jadet.AdministradorServicio.ClienteResponse guardarCliente(Jadet.AdministradorServicio.ClienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministrador/guardarCliente", ReplyAction="http://tempuri.org/IAdministrador/guardarClienteResponse")]
        System.Threading.Tasks.Task<Jadet.AdministradorServicio.ClienteResponse> guardarClienteAsync(Jadet.AdministradorServicio.ClienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministrador/bajaCliente", ReplyAction="http://tempuri.org/IAdministrador/bajaClienteResponse")]
        Jadet.AdministradorServicio.BaseResponse bajaCliente(Jadet.AdministradorServicio.ClienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministrador/bajaCliente", ReplyAction="http://tempuri.org/IAdministrador/bajaClienteResponse")]
        System.Threading.Tasks.Task<Jadet.AdministradorServicio.BaseResponse> bajaClienteAsync(Jadet.AdministradorServicio.ClienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministrador/cargarCliente", ReplyAction="http://tempuri.org/IAdministrador/cargarClienteResponse")]
        Jadet.AdministradorServicio.ClienteResponse cargarCliente(Jadet.AdministradorServicio.ClienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministrador/cargarCliente", ReplyAction="http://tempuri.org/IAdministrador/cargarClienteResponse")]
        System.Threading.Tasks.Task<Jadet.AdministradorServicio.ClienteResponse> cargarClienteAsync(Jadet.AdministradorServicio.ClienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministrador/subirFotos", ReplyAction="http://tempuri.org/IAdministrador/subirFotosResponse")]
        Jadet.AdministradorServicio.ArchivoResponse subirFotos(Jadet.AdministradorServicio.ArchivoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministrador/subirFotos", ReplyAction="http://tempuri.org/IAdministrador/subirFotosResponse")]
        System.Threading.Tasks.Task<Jadet.AdministradorServicio.ArchivoResponse> subirFotosAsync(Jadet.AdministradorServicio.ArchivoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministrador/cargarHistorialCliente", ReplyAction="http://tempuri.org/IAdministrador/cargarHistorialClienteResponse")]
        Jadet.AdministradorServicio.HistorialClienteResponse cargarHistorialCliente(Jadet.AdministradorServicio.ClienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministrador/cargarHistorialCliente", ReplyAction="http://tempuri.org/IAdministrador/cargarHistorialClienteResponse")]
        System.Threading.Tasks.Task<Jadet.AdministradorServicio.HistorialClienteResponse> cargarHistorialClienteAsync(Jadet.AdministradorServicio.ClienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministrador/guardarProducto", ReplyAction="http://tempuri.org/IAdministrador/guardarProductoResponse")]
        Jadet.AdministradorServicio.ProductoResponse guardarProducto(Jadet.AdministradorServicio.ProductoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministrador/guardarProducto", ReplyAction="http://tempuri.org/IAdministrador/guardarProductoResponse")]
        System.Threading.Tasks.Task<Jadet.AdministradorServicio.ProductoResponse> guardarProductoAsync(Jadet.AdministradorServicio.ProductoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministrador/bajaProducto", ReplyAction="http://tempuri.org/IAdministrador/bajaProductoResponse")]
        Jadet.AdministradorServicio.BaseResponse bajaProducto(Jadet.AdministradorServicio.ProductoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministrador/bajaProducto", ReplyAction="http://tempuri.org/IAdministrador/bajaProductoResponse")]
        System.Threading.Tasks.Task<Jadet.AdministradorServicio.BaseResponse> bajaProductoAsync(Jadet.AdministradorServicio.ProductoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministrador/cargarProducto", ReplyAction="http://tempuri.org/IAdministrador/cargarProductoResponse")]
        Jadet.AdministradorServicio.ProductoResponse cargarProducto(Jadet.AdministradorServicio.ProductoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministrador/cargarProducto", ReplyAction="http://tempuri.org/IAdministrador/cargarProductoResponse")]
        System.Threading.Tasks.Task<Jadet.AdministradorServicio.ProductoResponse> cargarProductoAsync(Jadet.AdministradorServicio.ProductoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministrador/listarProductos", ReplyAction="http://tempuri.org/IAdministrador/listarProductosResponse")]
        Jadet.AdministradorServicio.coleccionProductoResponse listarProductos(Jadet.AdministradorServicio.BaseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministrador/listarProductos", ReplyAction="http://tempuri.org/IAdministrador/listarProductosResponse")]
        System.Threading.Tasks.Task<Jadet.AdministradorServicio.coleccionProductoResponse> listarProductosAsync(Jadet.AdministradorServicio.BaseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministrador/listarNotas", ReplyAction="http://tempuri.org/IAdministrador/listarNotasResponse")]
        Jadet.AdministradorServicio.coleccionNotasResponse listarNotas(Jadet.AdministradorServicio.BaseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministrador/listarNotas", ReplyAction="http://tempuri.org/IAdministrador/listarNotasResponse")]
        System.Threading.Tasks.Task<Jadet.AdministradorServicio.coleccionNotasResponse> listarNotasAsync(Jadet.AdministradorServicio.BaseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministrador/verNota", ReplyAction="http://tempuri.org/IAdministrador/verNotaResponse")]
        Jadet.AdministradorServicio.NotaResponse verNota(Jadet.AdministradorServicio.NotaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministrador/verNota", ReplyAction="http://tempuri.org/IAdministrador/verNotaResponse")]
        System.Threading.Tasks.Task<Jadet.AdministradorServicio.NotaResponse> verNotaAsync(Jadet.AdministradorServicio.NotaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministrador/borrarNota", ReplyAction="http://tempuri.org/IAdministrador/borrarNotaResponse")]
        Jadet.AdministradorServicio.NotaResponse borrarNota(Jadet.AdministradorServicio.NotaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministrador/borrarNota", ReplyAction="http://tempuri.org/IAdministrador/borrarNotaResponse")]
        System.Threading.Tasks.Task<Jadet.AdministradorServicio.NotaResponse> borrarNotaAsync(Jadet.AdministradorServicio.NotaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministrador/generarGuias", ReplyAction="http://tempuri.org/IAdministrador/generarGuiasResponse")]
        Jadet.AdministradorServicio.GuiaResponse generarGuias(Jadet.AdministradorServicio.GuiaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministrador/generarGuias", ReplyAction="http://tempuri.org/IAdministrador/generarGuiasResponse")]
        System.Threading.Tasks.Task<Jadet.AdministradorServicio.GuiaResponse> generarGuiasAsync(Jadet.AdministradorServicio.GuiaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministrador/enviarRecordatorios", ReplyAction="http://tempuri.org/IAdministrador/enviarRecordatoriosResponse")]
        Jadet.AdministradorServicio.BaseResponse enviarRecordatorios(Jadet.AdministradorServicio.BaseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministrador/enviarRecordatorios", ReplyAction="http://tempuri.org/IAdministrador/enviarRecordatoriosResponse")]
        System.Threading.Tasks.Task<Jadet.AdministradorServicio.BaseResponse> enviarRecordatoriosAsync(Jadet.AdministradorServicio.BaseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministrador/cambiarEstatusPagina", ReplyAction="http://tempuri.org/IAdministrador/cambiarEstatusPaginaResponse")]
        Jadet.AdministradorServicio.BaseResponse cambiarEstatusPagina(Jadet.AdministradorServicio.BaseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministrador/cambiarEstatusPagina", ReplyAction="http://tempuri.org/IAdministrador/cambiarEstatusPaginaResponse")]
        System.Threading.Tasks.Task<Jadet.AdministradorServicio.BaseResponse> cambiarEstatusPaginaAsync(Jadet.AdministradorServicio.BaseRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAdministradorChannel : Jadet.AdministradorServicio.IAdministrador, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AdministradorClient : System.ServiceModel.ClientBase<Jadet.AdministradorServicio.IAdministrador>, Jadet.AdministradorServicio.IAdministrador {
        
        public AdministradorClient() {
        }
        
        public AdministradorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AdministradorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdministradorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdministradorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Jadet.AdministradorServicio.ClienteResponse guardarCliente(Jadet.AdministradorServicio.ClienteRequest request) {
            return base.Channel.guardarCliente(request);
        }
        
        public System.Threading.Tasks.Task<Jadet.AdministradorServicio.ClienteResponse> guardarClienteAsync(Jadet.AdministradorServicio.ClienteRequest request) {
            return base.Channel.guardarClienteAsync(request);
        }
        
        public Jadet.AdministradorServicio.BaseResponse bajaCliente(Jadet.AdministradorServicio.ClienteRequest request) {
            return base.Channel.bajaCliente(request);
        }
        
        public System.Threading.Tasks.Task<Jadet.AdministradorServicio.BaseResponse> bajaClienteAsync(Jadet.AdministradorServicio.ClienteRequest request) {
            return base.Channel.bajaClienteAsync(request);
        }
        
        public Jadet.AdministradorServicio.ClienteResponse cargarCliente(Jadet.AdministradorServicio.ClienteRequest request) {
            return base.Channel.cargarCliente(request);
        }
        
        public System.Threading.Tasks.Task<Jadet.AdministradorServicio.ClienteResponse> cargarClienteAsync(Jadet.AdministradorServicio.ClienteRequest request) {
            return base.Channel.cargarClienteAsync(request);
        }
        
        public Jadet.AdministradorServicio.ArchivoResponse subirFotos(Jadet.AdministradorServicio.ArchivoRequest request) {
            return base.Channel.subirFotos(request);
        }
        
        public System.Threading.Tasks.Task<Jadet.AdministradorServicio.ArchivoResponse> subirFotosAsync(Jadet.AdministradorServicio.ArchivoRequest request) {
            return base.Channel.subirFotosAsync(request);
        }
        
        public Jadet.AdministradorServicio.HistorialClienteResponse cargarHistorialCliente(Jadet.AdministradorServicio.ClienteRequest request) {
            return base.Channel.cargarHistorialCliente(request);
        }
        
        public System.Threading.Tasks.Task<Jadet.AdministradorServicio.HistorialClienteResponse> cargarHistorialClienteAsync(Jadet.AdministradorServicio.ClienteRequest request) {
            return base.Channel.cargarHistorialClienteAsync(request);
        }
        
        public Jadet.AdministradorServicio.ProductoResponse guardarProducto(Jadet.AdministradorServicio.ProductoRequest request) {
            return base.Channel.guardarProducto(request);
        }
        
        public System.Threading.Tasks.Task<Jadet.AdministradorServicio.ProductoResponse> guardarProductoAsync(Jadet.AdministradorServicio.ProductoRequest request) {
            return base.Channel.guardarProductoAsync(request);
        }
        
        public Jadet.AdministradorServicio.BaseResponse bajaProducto(Jadet.AdministradorServicio.ProductoRequest request) {
            return base.Channel.bajaProducto(request);
        }
        
        public System.Threading.Tasks.Task<Jadet.AdministradorServicio.BaseResponse> bajaProductoAsync(Jadet.AdministradorServicio.ProductoRequest request) {
            return base.Channel.bajaProductoAsync(request);
        }
        
        public Jadet.AdministradorServicio.ProductoResponse cargarProducto(Jadet.AdministradorServicio.ProductoRequest request) {
            return base.Channel.cargarProducto(request);
        }
        
        public System.Threading.Tasks.Task<Jadet.AdministradorServicio.ProductoResponse> cargarProductoAsync(Jadet.AdministradorServicio.ProductoRequest request) {
            return base.Channel.cargarProductoAsync(request);
        }
        
        public Jadet.AdministradorServicio.coleccionProductoResponse listarProductos(Jadet.AdministradorServicio.BaseRequest request) {
            return base.Channel.listarProductos(request);
        }
        
        public System.Threading.Tasks.Task<Jadet.AdministradorServicio.coleccionProductoResponse> listarProductosAsync(Jadet.AdministradorServicio.BaseRequest request) {
            return base.Channel.listarProductosAsync(request);
        }
        
        public Jadet.AdministradorServicio.coleccionNotasResponse listarNotas(Jadet.AdministradorServicio.BaseRequest request) {
            return base.Channel.listarNotas(request);
        }
        
        public System.Threading.Tasks.Task<Jadet.AdministradorServicio.coleccionNotasResponse> listarNotasAsync(Jadet.AdministradorServicio.BaseRequest request) {
            return base.Channel.listarNotasAsync(request);
        }
        
        public Jadet.AdministradorServicio.NotaResponse verNota(Jadet.AdministradorServicio.NotaRequest request) {
            return base.Channel.verNota(request);
        }
        
        public System.Threading.Tasks.Task<Jadet.AdministradorServicio.NotaResponse> verNotaAsync(Jadet.AdministradorServicio.NotaRequest request) {
            return base.Channel.verNotaAsync(request);
        }
        
        public Jadet.AdministradorServicio.NotaResponse borrarNota(Jadet.AdministradorServicio.NotaRequest request) {
            return base.Channel.borrarNota(request);
        }
        
        public System.Threading.Tasks.Task<Jadet.AdministradorServicio.NotaResponse> borrarNotaAsync(Jadet.AdministradorServicio.NotaRequest request) {
            return base.Channel.borrarNotaAsync(request);
        }
        
        public Jadet.AdministradorServicio.GuiaResponse generarGuias(Jadet.AdministradorServicio.GuiaRequest request) {
            return base.Channel.generarGuias(request);
        }
        
        public System.Threading.Tasks.Task<Jadet.AdministradorServicio.GuiaResponse> generarGuiasAsync(Jadet.AdministradorServicio.GuiaRequest request) {
            return base.Channel.generarGuiasAsync(request);
        }
        
        public Jadet.AdministradorServicio.BaseResponse enviarRecordatorios(Jadet.AdministradorServicio.BaseRequest request) {
            return base.Channel.enviarRecordatorios(request);
        }
        
        public System.Threading.Tasks.Task<Jadet.AdministradorServicio.BaseResponse> enviarRecordatoriosAsync(Jadet.AdministradorServicio.BaseRequest request) {
            return base.Channel.enviarRecordatoriosAsync(request);
        }
        
        public Jadet.AdministradorServicio.BaseResponse cambiarEstatusPagina(Jadet.AdministradorServicio.BaseRequest request) {
            return base.Channel.cambiarEstatusPagina(request);
        }
        
        public System.Threading.Tasks.Task<Jadet.AdministradorServicio.BaseResponse> cambiarEstatusPaginaAsync(Jadet.AdministradorServicio.BaseRequest request) {
            return base.Channel.cambiarEstatusPaginaAsync(request);
        }
    }
}
