//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SernaSistemas.Jadet.DAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotaTicket
    {
        public int Id { get; set; }
        public int IdNota { get; set; }
        public byte[] Ticket { get; set; }
        public Nullable<decimal> MontoMXN { get; set; }
        public Nullable<decimal> MontoUSD { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    
        public virtual Nota Nota { get; set; }
    }
}
