//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SernaSistemas.Jadet.DAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BDJadetEntities : DbContext
    {
        public BDJadetEntities()
            : base("name=BDJadetEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Catalogo> Catalogoes { get; set; }
        public virtual DbSet<Estatus> Estatus1 { get; set; }
        public virtual DbSet<TipoCatalogo> TipoCatalogoes { get; set; }
        public virtual DbSet<TipoEstatus> TipoEstatus1 { get; set; }
        public virtual DbSet<Rol> Rols { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
        public virtual DbSet<Detalle> Detalles { get; set; }
        public virtual DbSet<Nota> Notas { get; set; }
        public virtual DbSet<NotaComentario> NotaComentarios { get; set; }
        public virtual DbSet<NotaTicket> NotaTickets { get; set; }
        public virtual DbSet<Producto> Productoes { get; set; }
    
        public virtual ObjectResult<borrarCatalogo_Result> borrarCatalogo(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<borrarCatalogo_Result>("borrarCatalogo", idParameter);
        }
    
        public virtual ObjectResult<borrarEstatus_Result> borrarEstatus(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<borrarEstatus_Result>("borrarEstatus", idParameter);
        }
    
        public virtual ObjectResult<guardarCatalogo_Result> guardarCatalogo(Nullable<int> id, string nombre, Nullable<int> idTipoCatalogo)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var idTipoCatalogoParameter = idTipoCatalogo.HasValue ?
                new ObjectParameter("IdTipoCatalogo", idTipoCatalogo) :
                new ObjectParameter("IdTipoCatalogo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<guardarCatalogo_Result>("guardarCatalogo", idParameter, nombreParameter, idTipoCatalogoParameter);
        }
    
        public virtual ObjectResult<guardarEstatus_Result> guardarEstatus(Nullable<int> id, string nombre, Nullable<int> idTipoEstatus)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var idTipoEstatusParameter = idTipoEstatus.HasValue ?
                new ObjectParameter("IdTipoEstatus", idTipoEstatus) :
                new ObjectParameter("IdTipoEstatus", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<guardarEstatus_Result>("guardarEstatus", idParameter, nombreParameter, idTipoEstatusParameter);
        }
    
        public virtual ObjectResult<listarCatalogo_Result> listarCatalogo(Nullable<int> idTipoCatalogo, Nullable<int> idCatalogo)
        {
            var idTipoCatalogoParameter = idTipoCatalogo.HasValue ?
                new ObjectParameter("IdTipoCatalogo", idTipoCatalogo) :
                new ObjectParameter("IdTipoCatalogo", typeof(int));
    
            var idCatalogoParameter = idCatalogo.HasValue ?
                new ObjectParameter("IdCatalogo", idCatalogo) :
                new ObjectParameter("IdCatalogo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<listarCatalogo_Result>("listarCatalogo", idTipoCatalogoParameter, idCatalogoParameter);
        }
    
        public virtual ObjectResult<listarEstatus_Result> listarEstatus(Nullable<int> idTipoEstatus, Nullable<int> idEstatus)
        {
            var idTipoEstatusParameter = idTipoEstatus.HasValue ?
                new ObjectParameter("IdTipoEstatus", idTipoEstatus) :
                new ObjectParameter("IdTipoEstatus", typeof(int));
    
            var idEstatusParameter = idEstatus.HasValue ?
                new ObjectParameter("IdEstatus", idEstatus) :
                new ObjectParameter("IdEstatus", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<listarEstatus_Result>("listarEstatus", idTipoEstatusParameter, idEstatusParameter);
        }
    
        public virtual ObjectResult<listarTipoCatalogo_Result> listarTipoCatalogo(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<listarTipoCatalogo_Result>("listarTipoCatalogo", idParameter);
        }
    
        public virtual ObjectResult<listarTipoEstatus_Result> listarTipoEstatus(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<listarTipoEstatus_Result>("listarTipoEstatus", idParameter);
        }
    
        public virtual ObjectResult<borrarUsuario_Result> borrarUsuario(Nullable<System.Guid> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<borrarUsuario_Result>("borrarUsuario", idParameter);
        }
    
        public virtual ObjectResult<guardarUsuario_Result> guardarUsuario(Nullable<System.Guid> id, string nombre, string direccion, string telefono, byte[] foto, string usuario, byte[] passwd, Nullable<int> idRol, Nullable<int> zonaPaqueteria, Nullable<int> idEstatus)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(System.Guid));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var direccionParameter = direccion != null ?
                new ObjectParameter("Direccion", direccion) :
                new ObjectParameter("Direccion", typeof(string));
    
            var telefonoParameter = telefono != null ?
                new ObjectParameter("Telefono", telefono) :
                new ObjectParameter("Telefono", typeof(string));
    
            var fotoParameter = foto != null ?
                new ObjectParameter("Foto", foto) :
                new ObjectParameter("Foto", typeof(byte[]));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            var passwdParameter = passwd != null ?
                new ObjectParameter("Passwd", passwd) :
                new ObjectParameter("Passwd", typeof(byte[]));
    
            var idRolParameter = idRol.HasValue ?
                new ObjectParameter("IdRol", idRol) :
                new ObjectParameter("IdRol", typeof(int));
    
            var zonaPaqueteriaParameter = zonaPaqueteria.HasValue ?
                new ObjectParameter("ZonaPaqueteria", zonaPaqueteria) :
                new ObjectParameter("ZonaPaqueteria", typeof(int));
    
            var idEstatusParameter = idEstatus.HasValue ?
                new ObjectParameter("IdEstatus", idEstatus) :
                new ObjectParameter("IdEstatus", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<guardarUsuario_Result>("guardarUsuario", idParameter, nombreParameter, direccionParameter, telefonoParameter, fotoParameter, usuarioParameter, passwdParameter, idRolParameter, zonaPaqueteriaParameter, idEstatusParameter);
        }
    
        public virtual ObjectResult<iniciarSesion_Result> iniciarSesion(string usuario, byte[] passwd)
        {
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            var passwdParameter = passwd != null ?
                new ObjectParameter("Passwd", passwd) :
                new ObjectParameter("Passwd", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<iniciarSesion_Result>("iniciarSesion", usuarioParameter, passwdParameter);
        }
    
        public virtual ObjectResult<listarRol_Result> listarRol(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<listarRol_Result>("listarRol", idParameter);
        }
    
        public virtual ObjectResult<listarUsuario_Result> listarUsuario(Nullable<System.Guid> id, Nullable<int> idRol)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(System.Guid));
    
            var idRolParameter = idRol.HasValue ?
                new ObjectParameter("IdRol", idRol) :
                new ObjectParameter("IdRol", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<listarUsuario_Result>("listarUsuario", idParameter, idRolParameter);
        }
    
        public virtual int borrarComentario(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("borrarComentario", idParameter);
        }
    
        public virtual ObjectResult<borrarDetalle_Result> borrarDetalle(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<borrarDetalle_Result>("borrarDetalle", idParameter);
        }
    
        public virtual ObjectResult<borrarProducto_Result> borrarProducto(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<borrarProducto_Result>("borrarProducto", idParameter);
        }
    
        public virtual ObjectResult<guardarComentario_Result> guardarComentario(Nullable<int> id, Nullable<int> idNota, string comentario, Nullable<System.DateTime> fecha, Nullable<int> idAnterior)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var idNotaParameter = idNota.HasValue ?
                new ObjectParameter("IdNota", idNota) :
                new ObjectParameter("IdNota", typeof(int));
    
            var comentarioParameter = comentario != null ?
                new ObjectParameter("Comentario", comentario) :
                new ObjectParameter("Comentario", typeof(string));
    
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("Fecha", fecha) :
                new ObjectParameter("Fecha", typeof(System.DateTime));
    
            var idAnteriorParameter = idAnterior.HasValue ?
                new ObjectParameter("IdAnterior", idAnterior) :
                new ObjectParameter("IdAnterior", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<guardarComentario_Result>("guardarComentario", idParameter, idNotaParameter, comentarioParameter, fechaParameter, idAnteriorParameter);
        }
    
        public virtual ObjectResult<guardarDetalle_Result> guardarDetalle(Nullable<int> id, Nullable<int> idNota, Nullable<int> idProducto, Nullable<int> cantidad, Nullable<decimal> precioMXN, Nullable<decimal> precioUSD)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var idNotaParameter = idNota.HasValue ?
                new ObjectParameter("IdNota", idNota) :
                new ObjectParameter("IdNota", typeof(int));
    
            var idProductoParameter = idProducto.HasValue ?
                new ObjectParameter("IdProducto", idProducto) :
                new ObjectParameter("IdProducto", typeof(int));
    
            var cantidadParameter = cantidad.HasValue ?
                new ObjectParameter("Cantidad", cantidad) :
                new ObjectParameter("Cantidad", typeof(int));
    
            var precioMXNParameter = precioMXN.HasValue ?
                new ObjectParameter("PrecioMXN", precioMXN) :
                new ObjectParameter("PrecioMXN", typeof(decimal));
    
            var precioUSDParameter = precioUSD.HasValue ?
                new ObjectParameter("PrecioUSD", precioUSD) :
                new ObjectParameter("PrecioUSD", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<guardarDetalle_Result>("guardarDetalle", idParameter, idNotaParameter, idProductoParameter, cantidadParameter, precioMXNParameter, precioUSDParameter);
        }
    
        public virtual ObjectResult<guardarNota_Result> guardarNota(Nullable<int> folio, Nullable<System.DateTime> fecha, Nullable<int> idTipo, Nullable<int> idEstatus, Nullable<int> idPaqueteria, Nullable<System.Guid> idCliente, string guia, Nullable<System.DateTime> fechaEnvio, Nullable<decimal> montoMXN, Nullable<decimal> montoUSD, Nullable<decimal> saldoMXN, Nullable<decimal> saldoUSD)
        {
            var folioParameter = folio.HasValue ?
                new ObjectParameter("Folio", folio) :
                new ObjectParameter("Folio", typeof(int));
    
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("Fecha", fecha) :
                new ObjectParameter("Fecha", typeof(System.DateTime));
    
            var idTipoParameter = idTipo.HasValue ?
                new ObjectParameter("IdTipo", idTipo) :
                new ObjectParameter("IdTipo", typeof(int));
    
            var idEstatusParameter = idEstatus.HasValue ?
                new ObjectParameter("IdEstatus", idEstatus) :
                new ObjectParameter("IdEstatus", typeof(int));
    
            var idPaqueteriaParameter = idPaqueteria.HasValue ?
                new ObjectParameter("IdPaqueteria", idPaqueteria) :
                new ObjectParameter("IdPaqueteria", typeof(int));
    
            var idClienteParameter = idCliente.HasValue ?
                new ObjectParameter("IdCliente", idCliente) :
                new ObjectParameter("IdCliente", typeof(System.Guid));
    
            var guiaParameter = guia != null ?
                new ObjectParameter("Guia", guia) :
                new ObjectParameter("Guia", typeof(string));
    
            var fechaEnvioParameter = fechaEnvio.HasValue ?
                new ObjectParameter("FechaEnvio", fechaEnvio) :
                new ObjectParameter("FechaEnvio", typeof(System.DateTime));
    
            var montoMXNParameter = montoMXN.HasValue ?
                new ObjectParameter("MontoMXN", montoMXN) :
                new ObjectParameter("MontoMXN", typeof(decimal));
    
            var montoUSDParameter = montoUSD.HasValue ?
                new ObjectParameter("MontoUSD", montoUSD) :
                new ObjectParameter("MontoUSD", typeof(decimal));
    
            var saldoMXNParameter = saldoMXN.HasValue ?
                new ObjectParameter("SaldoMXN", saldoMXN) :
                new ObjectParameter("SaldoMXN", typeof(decimal));
    
            var saldoUSDParameter = saldoUSD.HasValue ?
                new ObjectParameter("SaldoUSD", saldoUSD) :
                new ObjectParameter("SaldoUSD", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<guardarNota_Result>("guardarNota", folioParameter, fechaParameter, idTipoParameter, idEstatusParameter, idPaqueteriaParameter, idClienteParameter, guiaParameter, fechaEnvioParameter, montoMXNParameter, montoUSDParameter, saldoMXNParameter, saldoUSDParameter);
        }
    
        public virtual ObjectResult<guardarProducto_Result> guardarProducto(Nullable<int> id, string sku, string nombre, string descripcion, Nullable<decimal> precioMXN, Nullable<decimal> precioUSD, Nullable<int> existencias, Nullable<bool> aplicaExistencias, byte[] foto, Nullable<int> idCatalogo, Nullable<int> idEstatus, Nullable<int> idTipo)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var skuParameter = sku != null ?
                new ObjectParameter("sku", sku) :
                new ObjectParameter("sku", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var precioMXNParameter = precioMXN.HasValue ?
                new ObjectParameter("PrecioMXN", precioMXN) :
                new ObjectParameter("PrecioMXN", typeof(decimal));
    
            var precioUSDParameter = precioUSD.HasValue ?
                new ObjectParameter("PrecioUSD", precioUSD) :
                new ObjectParameter("PrecioUSD", typeof(decimal));
    
            var existenciasParameter = existencias.HasValue ?
                new ObjectParameter("Existencias", existencias) :
                new ObjectParameter("Existencias", typeof(int));
    
            var aplicaExistenciasParameter = aplicaExistencias.HasValue ?
                new ObjectParameter("AplicaExistencias", aplicaExistencias) :
                new ObjectParameter("AplicaExistencias", typeof(bool));
    
            var fotoParameter = foto != null ?
                new ObjectParameter("Foto", foto) :
                new ObjectParameter("Foto", typeof(byte[]));
    
            var idCatalogoParameter = idCatalogo.HasValue ?
                new ObjectParameter("IdCatalogo", idCatalogo) :
                new ObjectParameter("IdCatalogo", typeof(int));
    
            var idEstatusParameter = idEstatus.HasValue ?
                new ObjectParameter("IdEstatus", idEstatus) :
                new ObjectParameter("IdEstatus", typeof(int));
    
            var idTipoParameter = idTipo.HasValue ?
                new ObjectParameter("IdTipo", idTipo) :
                new ObjectParameter("IdTipo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<guardarProducto_Result>("guardarProducto", idParameter, skuParameter, nombreParameter, descripcionParameter, precioMXNParameter, precioUSDParameter, existenciasParameter, aplicaExistenciasParameter, fotoParameter, idCatalogoParameter, idEstatusParameter, idTipoParameter);
        }
    
        public virtual ObjectResult<guardarTicket_Result> guardarTicket(Nullable<int> id, Nullable<int> idNota, byte[] ticket, Nullable<decimal> montoMXN, Nullable<decimal> montoUSD, Nullable<System.DateTime> fecha)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var idNotaParameter = idNota.HasValue ?
                new ObjectParameter("IdNota", idNota) :
                new ObjectParameter("IdNota", typeof(int));
    
            var ticketParameter = ticket != null ?
                new ObjectParameter("Ticket", ticket) :
                new ObjectParameter("Ticket", typeof(byte[]));
    
            var montoMXNParameter = montoMXN.HasValue ?
                new ObjectParameter("MontoMXN", montoMXN) :
                new ObjectParameter("MontoMXN", typeof(decimal));
    
            var montoUSDParameter = montoUSD.HasValue ?
                new ObjectParameter("MontoUSD", montoUSD) :
                new ObjectParameter("MontoUSD", typeof(decimal));
    
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("Fecha", fecha) :
                new ObjectParameter("Fecha", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<guardarTicket_Result>("guardarTicket", idParameter, idNotaParameter, ticketParameter, montoMXNParameter, montoUSDParameter, fechaParameter);
        }
    
        public virtual ObjectResult<listarComentarios_Result> listarComentarios(Nullable<int> id, Nullable<int> idNota)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var idNotaParameter = idNota.HasValue ?
                new ObjectParameter("IdNota", idNota) :
                new ObjectParameter("IdNota", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<listarComentarios_Result>("listarComentarios", idParameter, idNotaParameter);
        }
    
        public virtual ObjectResult<listarDetalle_Result> listarDetalle(Nullable<int> id, Nullable<int> idNota, Nullable<int> idProducto)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var idNotaParameter = idNota.HasValue ?
                new ObjectParameter("IdNota", idNota) :
                new ObjectParameter("IdNota", typeof(int));
    
            var idProductoParameter = idProducto.HasValue ?
                new ObjectParameter("IdProducto", idProducto) :
                new ObjectParameter("IdProducto", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<listarDetalle_Result>("listarDetalle", idParameter, idNotaParameter, idProductoParameter);
        }
    
        public virtual ObjectResult<listarNotas_Result> listarNotas(Nullable<int> folio, Nullable<System.DateTime> fecha, Nullable<int> idEstatus, Nullable<System.Guid> idCliente)
        {
            var folioParameter = folio.HasValue ?
                new ObjectParameter("Folio", folio) :
                new ObjectParameter("Folio", typeof(int));
    
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("Fecha", fecha) :
                new ObjectParameter("Fecha", typeof(System.DateTime));
    
            var idEstatusParameter = idEstatus.HasValue ?
                new ObjectParameter("IdEstatus", idEstatus) :
                new ObjectParameter("IdEstatus", typeof(int));
    
            var idClienteParameter = idCliente.HasValue ?
                new ObjectParameter("IdCliente", idCliente) :
                new ObjectParameter("IdCliente", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<listarNotas_Result>("listarNotas", folioParameter, fechaParameter, idEstatusParameter, idClienteParameter);
        }
    
        public virtual ObjectResult<listarProductos_Result> listarProductos(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<listarProductos_Result>("listarProductos", idParameter);
        }
    
        public virtual ObjectResult<listarTickets_Result> listarTickets(Nullable<int> id, Nullable<int> idNota)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var idNotaParameter = idNota.HasValue ?
                new ObjectParameter("IdNota", idNota) :
                new ObjectParameter("IdNota", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<listarTickets_Result>("listarTickets", idParameter, idNotaParameter);
        }
    
        public virtual int vaciarCarrito(Nullable<int> idCarrito)
        {
            var idCarritoParameter = idCarrito.HasValue ?
                new ObjectParameter("IdCarrito", idCarrito) :
                new ObjectParameter("IdCarrito", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("vaciarCarrito", idCarritoParameter);
        }
    }
}
