//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jadet.ClienteServicio {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseRequest", Namespace="http://schemas.datacontract.org/2004/07/SernaSistemas.Jadet.WCF.Modelos")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Jadet.ClienteServicio.ItemCarritoRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Jadet.ClienteServicio.CarritoRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Jadet.ClienteServicio.ArchivoRequest))]
    public partial class BaseRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ItemCarritoRequest", Namespace="http://schemas.datacontract.org/2004/07/SernaSistemas.Jadet.WCF.Modelos")]
    [System.SerializableAttribute()]
    public partial class ItemCarritoRequest : Jadet.ClienteServicio.BaseRequest {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CarritoRequest", Namespace="http://schemas.datacontract.org/2004/07/SernaSistemas.Jadet.WCF.Modelos")]
    [System.SerializableAttribute()]
    public partial class CarritoRequest : Jadet.ClienteServicio.BaseRequest {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ArchivoRequest", Namespace="http://schemas.datacontract.org/2004/07/SernaSistemas.Jadet.WCF.Modelos")]
    [System.SerializableAttribute()]
    public partial class ArchivoRequest : Jadet.ClienteServicio.BaseRequest {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaCargaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LongitudField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RutaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoArchivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime UltimaModificacionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaCarga {
            get {
                return this.FechaCargaField;
            }
            set {
                if ((this.FechaCargaField.Equals(value) != true)) {
                    this.FechaCargaField = value;
                    this.RaisePropertyChanged("FechaCarga");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Longitud {
            get {
                return this.LongitudField;
            }
            set {
                if ((this.LongitudField.Equals(value) != true)) {
                    this.LongitudField = value;
                    this.RaisePropertyChanged("Longitud");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ruta {
            get {
                return this.RutaField;
            }
            set {
                if ((object.ReferenceEquals(this.RutaField, value) != true)) {
                    this.RutaField = value;
                    this.RaisePropertyChanged("Ruta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoArchivo {
            get {
                return this.TipoArchivoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoArchivoField, value) != true)) {
                    this.TipoArchivoField = value;
                    this.RaisePropertyChanged("TipoArchivo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime UltimaModificacion {
            get {
                return this.UltimaModificacionField;
            }
            set {
                if ((this.UltimaModificacionField.Equals(value) != true)) {
                    this.UltimaModificacionField = value;
                    this.RaisePropertyChanged("UltimaModificacion");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseResponse", Namespace="http://schemas.datacontract.org/2004/07/SernaSistemas.Jadet.WCF.Modelos")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Jadet.ClienteServicio.ItemCarritoResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Jadet.ClienteServicio.CarritoResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Jadet.ClienteServicio.ColeccionCarritoResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Jadet.ClienteServicio.ArchivoResponse))]
    public partial class BaseResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ErrorNumeroField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMensaje {
            get {
                return this.ErrorMensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMensajeField, value) != true)) {
                    this.ErrorMensajeField = value;
                    this.RaisePropertyChanged("ErrorMensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ErrorNumero {
            get {
                return this.ErrorNumeroField;
            }
            set {
                if ((this.ErrorNumeroField.Equals(value) != true)) {
                    this.ErrorNumeroField = value;
                    this.RaisePropertyChanged("ErrorNumero");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ItemCarritoResponse", Namespace="http://schemas.datacontract.org/2004/07/SernaSistemas.Jadet.WCF.Modelos")]
    [System.SerializableAttribute()]
    public partial class ItemCarritoResponse : Jadet.ClienteServicio.BaseResponse {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CarritoResponse", Namespace="http://schemas.datacontract.org/2004/07/SernaSistemas.Jadet.WCF.Modelos")]
    [System.SerializableAttribute()]
    public partial class CarritoResponse : Jadet.ClienteServicio.BaseResponse {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ColeccionCarritoResponse", Namespace="http://schemas.datacontract.org/2004/07/SernaSistemas.Jadet.WCF.Modelos")]
    [System.SerializableAttribute()]
    public partial class ColeccionCarritoResponse : Jadet.ClienteServicio.BaseResponse {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Jadet.ClienteServicio.CarritoResponse[] ItemsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Jadet.ClienteServicio.CarritoResponse[] Items {
            get {
                return this.ItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemsField, value) != true)) {
                    this.ItemsField = value;
                    this.RaisePropertyChanged("Items");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ArchivoResponse", Namespace="http://schemas.datacontract.org/2004/07/SernaSistemas.Jadet.WCF.Modelos")]
    [System.SerializableAttribute()]
    public partial class ArchivoResponse : Jadet.ClienteServicio.BaseResponse {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ClienteServicio.ICliente")]
    public interface ICliente {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICliente/subirFoto", ReplyAction="http://tempuri.org/ICliente/subirFotoResponse")]
        Jadet.ClienteServicio.ArchivoResponse subirFoto(Jadet.ClienteServicio.ArchivoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICliente/subirFoto", ReplyAction="http://tempuri.org/ICliente/subirFotoResponse")]
        System.Threading.Tasks.Task<Jadet.ClienteServicio.ArchivoResponse> subirFotoAsync(Jadet.ClienteServicio.ArchivoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICliente/agregarACarrito", ReplyAction="http://tempuri.org/ICliente/agregarACarritoResponse")]
        Jadet.ClienteServicio.ItemCarritoResponse agregarACarrito(Jadet.ClienteServicio.ItemCarritoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICliente/agregarACarrito", ReplyAction="http://tempuri.org/ICliente/agregarACarritoResponse")]
        System.Threading.Tasks.Task<Jadet.ClienteServicio.ItemCarritoResponse> agregarACarritoAsync(Jadet.ClienteServicio.ItemCarritoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICliente/quitarDelCarrito", ReplyAction="http://tempuri.org/ICliente/quitarDelCarritoResponse")]
        Jadet.ClienteServicio.BaseResponse quitarDelCarrito(Jadet.ClienteServicio.ItemCarritoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICliente/quitarDelCarrito", ReplyAction="http://tempuri.org/ICliente/quitarDelCarritoResponse")]
        System.Threading.Tasks.Task<Jadet.ClienteServicio.BaseResponse> quitarDelCarritoAsync(Jadet.ClienteServicio.ItemCarritoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICliente/vaciarCarrito", ReplyAction="http://tempuri.org/ICliente/vaciarCarritoResponse")]
        Jadet.ClienteServicio.CarritoResponse vaciarCarrito(Jadet.ClienteServicio.BaseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICliente/vaciarCarrito", ReplyAction="http://tempuri.org/ICliente/vaciarCarritoResponse")]
        System.Threading.Tasks.Task<Jadet.ClienteServicio.CarritoResponse> vaciarCarritoAsync(Jadet.ClienteServicio.BaseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICliente/generarPedido", ReplyAction="http://tempuri.org/ICliente/generarPedidoResponse")]
        Jadet.ClienteServicio.BaseResponse generarPedido(Jadet.ClienteServicio.CarritoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICliente/generarPedido", ReplyAction="http://tempuri.org/ICliente/generarPedidoResponse")]
        System.Threading.Tasks.Task<Jadet.ClienteServicio.BaseResponse> generarPedidoAsync(Jadet.ClienteServicio.CarritoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICliente/verPedido", ReplyAction="http://tempuri.org/ICliente/verPedidoResponse")]
        Jadet.ClienteServicio.CarritoResponse verPedido(Jadet.ClienteServicio.CarritoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICliente/verPedido", ReplyAction="http://tempuri.org/ICliente/verPedidoResponse")]
        System.Threading.Tasks.Task<Jadet.ClienteServicio.CarritoResponse> verPedidoAsync(Jadet.ClienteServicio.CarritoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICliente/listarPedidos", ReplyAction="http://tempuri.org/ICliente/listarPedidosResponse")]
        Jadet.ClienteServicio.ColeccionCarritoResponse listarPedidos(Jadet.ClienteServicio.BaseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICliente/listarPedidos", ReplyAction="http://tempuri.org/ICliente/listarPedidosResponse")]
        System.Threading.Tasks.Task<Jadet.ClienteServicio.ColeccionCarritoResponse> listarPedidosAsync(Jadet.ClienteServicio.BaseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICliente/guardarPedido", ReplyAction="http://tempuri.org/ICliente/guardarPedidoResponse")]
        Jadet.ClienteServicio.BaseResponse guardarPedido(Jadet.ClienteServicio.CarritoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICliente/guardarPedido", ReplyAction="http://tempuri.org/ICliente/guardarPedidoResponse")]
        System.Threading.Tasks.Task<Jadet.ClienteServicio.BaseResponse> guardarPedidoAsync(Jadet.ClienteServicio.CarritoRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IClienteChannel : Jadet.ClienteServicio.ICliente, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClienteClient : System.ServiceModel.ClientBase<Jadet.ClienteServicio.ICliente>, Jadet.ClienteServicio.ICliente {
        
        public ClienteClient() {
        }
        
        public ClienteClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClienteClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClienteClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClienteClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Jadet.ClienteServicio.ArchivoResponse subirFoto(Jadet.ClienteServicio.ArchivoRequest request) {
            return base.Channel.subirFoto(request);
        }
        
        public System.Threading.Tasks.Task<Jadet.ClienteServicio.ArchivoResponse> subirFotoAsync(Jadet.ClienteServicio.ArchivoRequest request) {
            return base.Channel.subirFotoAsync(request);
        }
        
        public Jadet.ClienteServicio.ItemCarritoResponse agregarACarrito(Jadet.ClienteServicio.ItemCarritoRequest request) {
            return base.Channel.agregarACarrito(request);
        }
        
        public System.Threading.Tasks.Task<Jadet.ClienteServicio.ItemCarritoResponse> agregarACarritoAsync(Jadet.ClienteServicio.ItemCarritoRequest request) {
            return base.Channel.agregarACarritoAsync(request);
        }
        
        public Jadet.ClienteServicio.BaseResponse quitarDelCarrito(Jadet.ClienteServicio.ItemCarritoRequest request) {
            return base.Channel.quitarDelCarrito(request);
        }
        
        public System.Threading.Tasks.Task<Jadet.ClienteServicio.BaseResponse> quitarDelCarritoAsync(Jadet.ClienteServicio.ItemCarritoRequest request) {
            return base.Channel.quitarDelCarritoAsync(request);
        }
        
        public Jadet.ClienteServicio.CarritoResponse vaciarCarrito(Jadet.ClienteServicio.BaseRequest request) {
            return base.Channel.vaciarCarrito(request);
        }
        
        public System.Threading.Tasks.Task<Jadet.ClienteServicio.CarritoResponse> vaciarCarritoAsync(Jadet.ClienteServicio.BaseRequest request) {
            return base.Channel.vaciarCarritoAsync(request);
        }
        
        public Jadet.ClienteServicio.BaseResponse generarPedido(Jadet.ClienteServicio.CarritoRequest request) {
            return base.Channel.generarPedido(request);
        }
        
        public System.Threading.Tasks.Task<Jadet.ClienteServicio.BaseResponse> generarPedidoAsync(Jadet.ClienteServicio.CarritoRequest request) {
            return base.Channel.generarPedidoAsync(request);
        }
        
        public Jadet.ClienteServicio.CarritoResponse verPedido(Jadet.ClienteServicio.CarritoRequest request) {
            return base.Channel.verPedido(request);
        }
        
        public System.Threading.Tasks.Task<Jadet.ClienteServicio.CarritoResponse> verPedidoAsync(Jadet.ClienteServicio.CarritoRequest request) {
            return base.Channel.verPedidoAsync(request);
        }
        
        public Jadet.ClienteServicio.ColeccionCarritoResponse listarPedidos(Jadet.ClienteServicio.BaseRequest request) {
            return base.Channel.listarPedidos(request);
        }
        
        public System.Threading.Tasks.Task<Jadet.ClienteServicio.ColeccionCarritoResponse> listarPedidosAsync(Jadet.ClienteServicio.BaseRequest request) {
            return base.Channel.listarPedidosAsync(request);
        }
        
        public Jadet.ClienteServicio.BaseResponse guardarPedido(Jadet.ClienteServicio.CarritoRequest request) {
            return base.Channel.guardarPedido(request);
        }
        
        public System.Threading.Tasks.Task<Jadet.ClienteServicio.BaseResponse> guardarPedidoAsync(Jadet.ClienteServicio.CarritoRequest request) {
            return base.Channel.guardarPedidoAsync(request);
        }
    }
}
