name: .NET

on:
  push:
    branches: [ desarrollo ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore ./SernaSistemas.Jadet.Data/SernaSistemas.Jadet.Data.csproj
    - name: Build Data project
      run: dotnet build --no-restore ./SernaSistemas.Jadet.Data/SernaSistemas.Jadet.Data.csproj
    - name: Test Data project
      run: dotnet test --no-build --verbosity normal  ./SernaSistemas.Jadet.Data/SernaSistemas.Jadet.Data.csproj
